#!/usr/bin/env bash

main()
{
    dirname "$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE}")")")")"
}

bin()
{
    echo "$(main)/bin"
}

COMMIT_MSG_FILE="$1"
MESSAGE="$(cat "${COMMIT_MSG_FILE}")"

[[ "${LEGACY_COMMIT_MESSAGE}" -ne 1 ]] || exit 0

result="$("$(bin)"/cog verify "${MESSAGE}" |& cat)"
echo "$result"

if echo "${result}" | grep -q "(not committed) - now"; then
    echo "${MESSAGE}" | "$(bin)"/insert-icon > "${COMMIT_MSG_FILE}"
else
    echo "See https://www.conventionalcommits.org/en/v1.0.0"
    exit 1
fi
