#!/usr/bin/env bash
[[ -n "${_QA_TOOLS_DISPATCHING:-}" ]] && exit 0
export _QA_TOOLS_DISPATCHING=1
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/dispatcher.sh"
dispatch "$(basename "$0")" "$@"
