#! /usr/bin/env bash
tests_dir()
{
    dirname "$(readlink -f "${BASH_SOURCE}")"
}

lib_dir()
{
    echo "$(tests_dir)/lib"
}

. "$(lib_dir)"/functions

for testfile in "$(tests_dir)"/*-test; do
    . "${testfile}"
    echo -e "\n----------\n"
done

PASSED="$((TESTS - ERRORS))"
echo -e "${PASSED} passed tests / ${TESTS} tests - ${ERRORS} errors."
