#! /usr/bin/env bash
tests_dir()
{
    dirname "$(readlink -f "${BASH_SOURCE}")"
}

lib_dir()
{
    echo "$(tests_dir)/lib"
}

. "$(lib_dir)"/functions

if [ -z "$1" ]; then
    for testfile in "$(tests_dir)"/*-test; do
        . "${testfile}"
        echo -e "\n----------\n"
    done
else
    if [ -e "$1" ]; then
        . "$1"
        echo -e "\n----------\n"
    else
        echo "File not found: $1"
        exit 1
    fi
fi

PASSED="$((TESTS - ERRORS))"
echo -e "${PASSED} passed tests / ${TESTS} tests - ${ERRORS} errors."
