#! /usr/bin/env bash

[ -n "${ERRORS}" ] || export ERRORS="${ERRORS:-0}"
[ -n "${TESTS}" ] || export TESTS="${TESTS:-0}"

# Assert two strings are equal
#
# Usage:
#   assert_equals "string 1" "string 2" "message"
function assert_equals {    
    local string1="$1"
    local string2="$2"
    local message="$3"
    local fails="\u2718"
    local succeed="\u2714"
    local result=0

    ((TESTS++))

    [ -n "${message}" ] || {
        message="Assert \e[34m'${string1}'\e[0m equals \e[35m'${string2}'\e[0m."
    }

    local diff="$(diff  <(echo "${string1}" ) <(echo "${string2}"))"

    if [ -z "${diff}" ]; then
        echo -e "\e[32m${succeed}\e[0m ${message}"
    else
        ((ERRORS++))

        result=1
        echo -e "\e[31m${fails}\e[0m ${message}"
        echo -e "\e[2m${diff}\e[22m"
    fi
    
    return $result
}

# Create a temporary file with a given content
#
# Usage:
#   tempfile=$(new_temp_file "Some content")
function new_temp_file {
    local file="$(mktemp /tmp/qa-tools-temp-XXXXXXXXXX)"
    local content="$1"

    echo "${content}" > "${file}"
    echo "${file}"
}
